version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  go: circleci/go@1.11.0
jobs:
  build:
    executor:
      name: go/default
      tag: "1.22"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
workflows:
  run_tests_and_deploy:
    jobs:
      - build
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: main